version: "3"
services:
  rabbitmq:
    build:
      context: .
      args:
        - BUILD_ENV
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_ADMIN_PORT}:15672
    volumes:
      - ${RABBITMQ_STORAGE}:/var/lib/rabbitmq
